module.exports={
  configureWebpack:{
    resolve:{
      extensions:['vue'],
      alias:{
        'assets':'@/assets',
        'common':'@/common',
        'components':'@/components',
        'network':'@/network',
        'views':'@/views',
      }
    }
  }
}